apiVersion: garden.io/v2
kind: Project
name: d20
dotIgnoreFile: .gitignore
environments:
  - name: local

providers:
  - name: local-kubernetes
    environments: [local]
    context: k3d-d20
    namespace:
      name: d20
    setupIngressController: false
    deploymentRegistry:
      hostname: d20-registry.localhost
      port: 5001
      insecure: true
      namespace: d20

sources:
  - name: qwinto
    repositoryUrl: git@github.com:ravecat/qwinto.git#master

---
kind: Deploy
type: kubernetes
name: backend
spec:
  manifestFiles:
    - manifests/*.yaml

---
kind: Build
type: exec
name: d20-setup
buildAtSource: true
spec:
  command: [mix, setup]

---
kind: Deploy
type: exec
name: d20
dependencies:
  - build.d20-setup
  - deploy.backend
spec:
  persistent: true
  deployCommand: [mix, serve]
  env:
    PHX_HOST: d20.localhost
    PHX_URL_PORT: "80"
    VITE_URL_HOST: vite.d20.localhost
