apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: d20
servers: 1
agents: 0
image: rancher/k3s:v1.30.6-k3s1
kubeAPI:
  host: 127.0.0.1
  hostIP: 127.0.0.1
  hostPort: "6445"
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: d20-registry
    host: 127.0.0.1
    hostPort: "5001"
